//
//  LoginPresenter.swift
//  Furdresser
//
//  Created by Iga Hupalo on 24/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol LoginPresenterInput {
    
}

protocol LoginPresenterOutput: AnyObject {
    func setEmailError(message: String?)
    func setPasswordError(message: String?)
}

class LoginPresenter: LoginPresenterInput {
    
    weak var output: LoginPresenterOutput?
    
    // MARK: Presentation logic

    func setEmailError(message: String?) {
        output?.setEmailError(message: message)
    }

    func setPasswordError(message: String?) {
        output?.setPasswordError(message: message)
    }
}
