//
//  AuthModels.swift
//  Furdresser
//
//  Created by Iga Hupalo on 25/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct ValidateEmail {
    struct Request {
        let email: String?
    }

    struct Response {
        let isValid: Bool
        let message: String?
    }
}

struct ValidatePassword {
    struct Request {
        let password: String?
    }

    struct Response {
        let isValid: Bool
        let message: String?
    }
}

struct LogIn {
    struct Request {
        let email: String
        let password: String
    }
}
