//
//  AppointmentDetailsConfigurator.swift
//  Furdresser
//
//  Created by Iga Hupalo on 24/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension AppointmentDetailsInteractor: AppointmentDetailsViewControllerOutput, AppointmentDetailsRouterDataSource, AppointmentDetailsRouterDataDestination {
}

extension AppointmentDetailsPresenter: AppointmentDetailsInteractorOutput {
}

class AppointmentDetailsConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = AppointmentDetailsConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: AppointmentDetailsViewController) {
        
        let presenter = AppointmentDetailsPresenter()
        presenter.output = viewController
        
        let interactor = AppointmentDetailsInteractor()
        interactor.output = presenter
        
        let router = AppointmentDetailsRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
