//
//  SettingsInteractor.swift
//  Furdresser
//
//  Created by Iga Hupalo on 27/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol SettingsInteractorInput {
    
}

protocol SettingsInteractorOutput {
    
}

protocol SettingsDataSource {
    
}

protocol SettingsDataDestination {
    
}

class SettingsInteractor: SettingsInteractorInput, SettingsDataSource, SettingsDataDestination {
    
    var output: SettingsInteractorOutput?

    private var authWorker = AuthWorker()

    // MARK: Business logic
    
    func logOut() {
        authWorker.logOut()
    }
}
