//
//  SettingsConfigurator.swift
//  Furdresser
//
//  Created by Iga Hupalo on 27/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension SettingsInteractor: SettingsViewControllerOutput, SettingsRouterDataSource, SettingsRouterDataDestination {
}

extension SettingsPresenter: SettingsInteractorOutput {
}

class SettingsConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = SettingsConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: SettingsViewController) {
        
        let presenter = SettingsPresenter()
        presenter.output = viewController
        
        let interactor = SettingsInteractor()
        interactor.output = presenter
        
        let router = SettingsRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
