//
//  SettingsPresenter.swift
//  Furdresser
//
//  Created by Iga Hupalo on 27/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol SettingsPresenterInput {
    
}

protocol SettingsPresenterOutput: AnyObject {
    
}

class SettingsPresenter: SettingsPresenterInput {
    
    weak var output: SettingsPresenterOutput?
    
    // MARK: Presentation logic
    
}
