//
//  StartConfigurator.swift
//  Furdresser
//
//  Created by Iga Hupalo on 24/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension StartInteractor: StartViewControllerOutput, StartRouterDataSource, StartRouterDataDestination {
}

extension StartPresenter: StartInteractorOutput {
}

class StartConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = StartConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: StartViewController) {
        
        let presenter = StartPresenter()
        presenter.output = viewController
        
        let interactor = StartInteractor()
        interactor.output = presenter
        
        let router = StartRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
