//
//  StartInteractor.swift
//  Furdresser
//
//  Created by Iga Hupalo on 24/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol StartInteractorInput {
    
}

protocol StartInteractorOutput {
    
}

protocol StartDataSource {
    
}

protocol StartDataDestination {
    
}

class StartInteractor: StartInteractorInput, StartDataSource, StartDataDestination {
    
    var output: StartInteractorOutput?
    
    // MARK: Business logic
    

}
