//
//  SplashLoadingConfigurator.swift
//  Furdresser
//
//  Created by Iga Hupalo on 27/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension SplashLoadingInteractor: SplashLoadingViewControllerOutput, SplashLoadingRouterDataSource, SplashLoadingRouterDataDestination {
}

extension SplashLoadingPresenter: SplashLoadingInteractorOutput {
}

class SplashLoadingConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = SplashLoadingConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: SplashLoadingViewController) {
        
        let presenter = SplashLoadingPresenter()
        presenter.output = viewController
        
        let interactor = SplashLoadingInteractor()
        interactor.output = presenter
        
        let router = SplashLoadingRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
