//
//  GroomerTabBarViewController.swift
//  Furdresser
//
//  Created by Iga Hupalo on 24/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol GroomerTabBarViewControllerInput {
    
}

protocol GroomerTabBarViewControllerOutput {
    
}

class GroomerTabBarViewController: UITabBarController, GroomerTabBarViewControllerInput, GroomerTabBarPresenterOutput {
    
    var output: GroomerTabBarViewControllerOutput?
    var router: GroomerTabBarRouter?
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        GroomerTabBarConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        router?.passDataToChildTabs()
    }
}
