//
//  GroomerTabBarConfigurator.swift
//  Furdresser
//
//  Created by Iga Hupalo on 24/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension GroomerTabBarInteractor: GroomerTabBarViewControllerOutput, GroomerTabBarRouterDataSource, GroomerTabBarRouterDataDestination {
}

extension GroomerTabBarPresenter: GroomerTabBarInteractorOutput {
}

class GroomerTabBarConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = GroomerTabBarConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: GroomerTabBarViewController) {
        
        let presenter = GroomerTabBarPresenter()
        presenter.output = viewController
        
        let interactor = GroomerTabBarInteractor()
        interactor.output = presenter
        
        let router = GroomerTabBarRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
