//
//  GroomerTabBarRouter.swift
//  Furdresser
//
//  Created by Iga Hupalo on 24/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol GroomerTabBarRouterInput {
    
}

protocol GroomerTabBarRouterDataSource: AnyObject {
    var currentUser: User? { get }
}

protocol GroomerTabBarRouterDataDestination: AnyObject {
    var currentUser: User? { get set }
}

class GroomerTabBarRouter: GroomerTabBarRouterInput {
    
    weak var viewController: GroomerTabBarViewController!
    weak private var dataSource: GroomerTabBarRouterDataSource!
    weak var dataDestination: GroomerTabBarRouterDataDestination!
    
    init(viewController: GroomerTabBarViewController, dataSource: GroomerTabBarRouterDataSource, dataDestination: GroomerTabBarRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }

    // MARK: Communication

    func passDataToChildTabs() {
        viewController.viewControllers?.forEach { child in
            if let navigationController = child as? UINavigationController,
               let appointmentsViewController = navigationController.viewControllers[0] as? AppointmentsViewController {
                appointmentsViewController.router?.dataDestination.user = dataSource.currentUser
            }
        }
    }
}
