//
//  GroomerTabBarPresenter.swift
//  Furdresser
//
//  Created by Iga Hupalo on 24/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol GroomerTabBarPresenterInput {
    
}

protocol GroomerTabBarPresenterOutput: AnyObject {
    
}

class GroomerTabBarPresenter: GroomerTabBarPresenterInput {
    
    weak var output: GroomerTabBarPresenterOutput?
    
    // MARK: Presentation logic
    
}
