//
//  ManagerTabBarPresenter.swift
//  Furdresser
//
//  Created by Iga Hupalo on 05/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol ManagerTabBarPresenterInput {
    
}

protocol ManagerTabBarPresenterOutput: class {
    
}

class ManagerTabBarPresenter: ManagerTabBarPresenterInput {
    
    weak var output: ManagerTabBarPresenterOutput?
    
    // MARK: Presentation logic
    
}
