//
//  ManagerTabBarRouter.swift
//  Furdresser
//
//  Created by Iga Hupalo on 05/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol ManagerTabBarRouterInput {
    
}

protocol ManagerTabBarRouterDataSource: AnyObject {
    var currentUser: User? { get }
}

protocol ManagerTabBarRouterDataDestination: AnyObject {
    var currentUser: User? { get set }
}

class ManagerTabBarRouter: ManagerTabBarRouterInput {
    
    weak var viewController: ManagerTabBarViewController!
    weak private var dataSource: ManagerTabBarRouterDataSource!
    weak var dataDestination: ManagerTabBarRouterDataDestination!
    
    init(viewController: ManagerTabBarViewController, dataSource: ManagerTabBarRouterDataSource, dataDestination: ManagerTabBarRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToChildTabs() {
        viewController.viewControllers?.forEach { child in
            if let navigationController = child as? UINavigationController,
               let appointmentsViewController = navigationController.viewControllers[0] as? AppointmentsViewController {
                appointmentsViewController.router?.dataDestination.user = dataSource.currentUser
            }
        }
    }
}
