//
//  ManagerTabBarViewController.swift
//  Furdresser
//
//  Created by Iga Hupalo on 05/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol ManagerTabBarViewControllerInput {
    
}

protocol ManagerTabBarViewControllerOutput {
    
}

class ManagerTabBarViewController: UITabBarController, ManagerTabBarViewControllerInput, ManagerTabBarPresenterOutput {
    
    var output: ManagerTabBarViewControllerOutput?
    var router: ManagerTabBarRouter?
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        ManagerTabBarConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        router?.passDataToChildTabs()
    }
}
