//
//  ManagerTabBarInteractor.swift
//  Furdresser
//
//  Created by Iga Hupalo on 05/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol ManagerTabBarInteractorInput {
    
}

protocol ManagerTabBarInteractorOutput {
    
}

protocol ManagerTabBarDataSource {
    
}

protocol ManagerTabBarDataDestination {
    
}

class ManagerTabBarInteractor: ManagerTabBarInteractorInput, ManagerTabBarDataSource, ManagerTabBarDataDestination {
    
    var output: ManagerTabBarInteractorOutput?

    var currentUser: User?
    
    // MARK: Business logic
    

}
